<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dummyRegistration" nsURI="http://www.eclipse.org/ocl/test/2018/DummyRegistration.ecore"
    nsPrefix="dummy">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The dummy registration ensures that the EcorePlugin sees a genmodel and so establishes a URI mapping for this test plugin."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DummyClass"/>
</ecore:EPackage>
