#
# The Buckminster 'build' build step follows the 'fetch' step to sort out ASM3 difficulties: (See Bug 432088, 432092)
#
# Note that Buckminster 4.5 requires -noverify; see Bug 471115, options are shown in buckminster-tests.png
#
# -Dcheckout.location=${WORKSPACE}
# -Dreference.repository=https://hudson.eclipse.org/ocl/job/${JOB_NAME}/lastSuccessfulBuild/artifact/MDT-OCL.p2.repository/
# -Xmx2g
# -noverify
#
# Future note: it might be better to have fetch,build,asm3,asm5,tests,packaging steps.
#
setpref complianceLevel=1.8

# We import a target definition which will be our API Base Line
importtargetdefinition "file://${checkout.location}/org.eclipse.ocl.git/releng/org.eclipse.ocl.releng.buckminster/APIBaseLine.target"
addbaseline -A "Eclipse OCL API Base Line"

#install "http://download.eclipse.org/eclipse/updates/4.6milestones" "org.eclipse.jdt"

# We set the path of the new target platform
setpref targetPlatformPath="${checkout.location}/buildroot/target.platform"

import --properties "${checkout.location}/buildroot/build.properties" "org.eclipse.ocl.git/releng/org.eclipse.ocl.releng.buckminster/releng/ocl-all.mspec"

build

#perform -DtargetPlatformPath="${checkout.location}/buildroot/target.platform" --properties "${checkout.location}/buildroot/build.properties" "org.eclipse.ocl.releng.buckminster:buckminster#create.javadoc"

# OCL Core Tests
junit --launch "org.eclipse.ocl.ecore.tests/launches/org.eclipse.ocl.ecore.tests\ \(Standalone\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.ecore.tests.xml"
junit --launch "org.eclipse.ocl.ecore.tests/launches/org.eclipse.ocl.ecore.tests\ \(Standalone\ Backtracking\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.ecore.backtracking.tests.xml"
junit --launch "org.eclipse.ocl.ecore.tests/launches/org.eclipse.ocl.ecore.tests\ \(Plugin).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.ecore.plugin.tests.xml"

junit --launch "org.eclipse.ocl.uml.tests/launches/org.eclipse.ocl.uml.tests\ \(Standalone\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.uml.tests.xml"
junit --launch "org.eclipse.ocl.uml.tests/launches/org.eclipse.ocl.uml.tests\ \(Standalone\ Backtracking\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.uml.backtracking.tests.xml"
junit --launch "org.eclipse.ocl.uml.tests/launches/org.eclipse.ocl.uml.tests\ \(Plugin\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.uml.plugin.tests.xml"

# OCL Tools Tests
junit --launch "org.eclipse.ocl.examples.tests/.launches/OCL\ All\ Examples\ Tests\ \(Standalone\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.tests.standalone.xml"
junit --launch "org.eclipse.ocl.examples.tests/.launches/OCL\ All\ Examples\ Tests\ \(Plugin\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.tests.plugin.xml"
#
junit --launch "org.eclipse.ocl.examples.xtext.tests/.settings/org.eclipse.ocl.examples.xtext.tests\ \(standalone\).launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.xtext.tests.xml"
junit --launch "org.eclipse.ocl.examples.xtext.tests/.settings/org.eclipse.ocl.examples.xtext.tests\ \(plugin\).launch" --flatXML --maxTimeAwaitJunitReport 60 --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.xtext.plugin.tests.xml"
#
junit --launch "org.eclipse.ocl.examples.eventmanager.tests/EventManagerTests.launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.eventmanager.tests.xml"
junit --launch "org.eclipse.ocl.examples.impactanalyzer.tests/ImpactAnalysisTests with TracebackSteps.launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.impactanalyzer.tracebacksteps.tests.xml"
junit --launch "org.eclipse.ocl.examples.impactanalyzer.tests/ImpactAnalysisTests with Traceback+UnusedChecks.launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.impactanalyzer.tracebacksteps_with_unused.tests.xml"
junit --launch "org.eclipse.ocl.examples.impactanalyzer.tests/ImpactAnalysisTests with NavigationSteps.launch" --flatXML --output "${checkout.location}/MDT-OCL.test.results/org.eclipse.ocl.examples.impactanalyzer.navigationsteps.tests.xml"

perform --properties "${checkout.location}/buildroot/build.properties" "-Dbuckminster.reference.repository=${reference.repository}" "org.eclipse.ocl.releng.build:eclipse.feature#build" 